name: flutter_trivia
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  dio: ^5.4.1
  flutter:
    sdk: flutter
  translator: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9

flutter:
  uses-material-design: true
